name: Build and deploy container app to Azure Web App - studentperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: studentperformance               # <-- Your Azure Web App name               # Or remove if you’re not using slots
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: studentperformance2.azurecr.io/studentperformance:latest
